version: 2

sources:
  - name: bikeflow_raw
    database: "{{ env_var('GOOGLE_CLOUD_PROJECT', 'bikeflow-sp-dezoomcamp') }}"
    schema: bikeflow_raw
    tables:
      - name: station_status_raw
        columns:
          - name: station_id
            tests:
              - not_null
          - name: ingested_at
            tests:
              - not_null

      - name: station_information_raw
        columns:
          - name: station_id
            tests:
              - not_null
          - name: ingested_at
            tests:
              - not_null
